apiVersion: v1
kind: Service
metadata: 
  name: scheduleservice-service
  namespace: mps
spec: 
  selector: 
    app: scheduleservice
  ports: 
    - port: 8080
      targetPort: 8080
  type: NodePort

  
