services :
  gateway :
    # build : ./Gateway.API
    image: krishnatr/gateway-api:latest
    container_name: api-gateway-device-management-system
    ports :
      - "6000:8080"
    depends_on  :
      - usermanagement
      - metermanagement
      - datacollection
      - eventservice
      - scheduleservice

  usermanagement :
      # build : ./UserManagementService
      image: krishnatr/user-management-service:latest
      container_name: user-management-service
      ports :
        - "6001:8080" 
  metermanagement :
      # build : ./MeterManagementService
      image: krishnatr/meter-management-service:latest
      container_name: meter-management-service
      ports :
        - "6002:8080"
      depends_on : 
          meter_api_db :
            condition : service_healthy
      environment: 
             - ASPNETCORE_ENVIRONMENT=Development
             - ConnectionStrings__MeterDb=Host=meter_api_db;Port=5432;Database=SE_MPS_MeterDb;Username=postgres;Password=password
  
  meter_api_db : 
      image : postgres:15
      container_name: meter_api_db
      restart : always
      environment : 
        POSTGRES_DB : SE_MPS_MeterDb
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password
      volumes:
        - meterapi_pgdata:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

  datacollection :
      # build : ./DataCollectionService
      image: krishnatr/data-collection-service:latest
      container_name: data-collection-service
      ports :
        - "6003:8080"
  eventservice :
      # build : ./EventService
      image: krishnatr/event-service:latest
      container_name: event-service
      ports : 
        - "6004:8080"
  scheduleservice : 
      # build : ./ScheduleService
      image: krishnatr/schedule-service:latest
      container_name: schedule-service
      ports :
        - "6005:8080"
volumes:
  meterapi_pgdata: 

  
  